[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "cap_anndata"
version = "0.6.0"
description = "Partial read/write of AnnData (h5ad) files for low-memory operations with large datasets."
readme = "README.md"
requires-python = ">=3.9"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
    { name = "R. Mukhin", email = "roman@ebookapplications.com" },
    { name = "A. Isaev" },
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.23.5",
    "pandas>=2.2.0",
    "anndata>=0.10.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "flake8",
]

[project.urls]
Homepage = "https://github.com/cellannotation/cap-anndata"
"Bug Tracker" = "https://github.com/cellannotation/cap-anndata/issues"
Changelog = "https://github.com/cellannotation/cap-anndata/blob/main/CHANGELOG.md"
Documentation = "https://github.com/cellannotation/cap-anndata/blob/main/HOWTO.md"

[tool.setuptools.packages.find]
include = ["cap_anndata*"]

[tool.pytest.ini_options]
testpaths = ["test"]
